### ISSUE TITLE
オフィスアワーの参加登録をスプレッドシートに記入する

### ISSUE THREAD

**Issue by kochigami** [Hinako-Suzuki/google-step-tsp#3]
集合時間を忘れたので，また今度教えて！ メー 
by ヤギ1/2

**Comment by YunaShibata0503** [comment]
26日火曜19時だった気がする！

**Comment by kochigami** [comment]
ありがとう！
スプレッドシート記入しておいたので，何か間違いあったら教えてね！

**Comment by kochigami** [comment]
あ，一人ずつ名前を追加するみたい・・・

１回目のスライドを見ながら一様埋めたんだけど，
間違っているかもしれないので（ごめんね），みんな確認お願いします！

副村長にも後でオフィスアワーに何をやったか伝えるね！！

**Comment by YunaShibata0503** [comment]
合ってた！やぎさんありがとう！
みんなもメールアドレス打つところあるから一回開いた方が良いと思われるよー！

**Comment by Hinako-Suzuki** [comment]
合ってたよー！ありがとう！！

**Comment by kochigami** [comment]
今日のオフィスアワーは，森タワーに入る前に一旦みんなで集合する必要がありそう．
目印要員として，森タワーの受付の前に18時50分くらいにはいるようにするね！！
スプレッドシートに入館番号など情報更新があったので，必要そうだったら確認してね！

集合に失敗した時用に念の為・・・
私はガラケーユーザーなので，パソコンでslackなどを見る時に目の前のクモのオブジェの近くに移動するかも！
何かあったらこのissueで連絡するね！みんなもよろしくね :)

**Comment by jhjgs** [comment]
🙆‍♀️

**Comment by Hinako-Suzuki** [comment]
了解です！ありがとう！！

**Comment by hayatoito** [comment]
あーごめんなさい。はっきり書いておくべきでした...。すいませんです。

Team C に関しては、代表者の名前とともに、同伴者の名前も全員登録したので、別々にきてもおそらく問題ないと思います！入館番号「0612」と代表者の名前と（必要であれば自分の名前も？）を伝えれば、森ビルの入館証をもらえると思います！

念の為、コピペ。他5名となっていますが、同伴者の名前もそれぞれ登録しました。
```
入館予約番号：0612
＜登録内容詳細＞
ご来訪者：Kanae Kochigami 様  他5名
ご訪問先：グーグル合同会社    Hayato Ito
訪問先：44F
ご来訪日時：2018/6/26 19:00
```

**Comment by Hinako-Suzuki** [comment]
了解しました！ありがとうございます！

**Comment by kochigami** [comment]
ありがとうございます！

**Comment by hayatoito** [comment]
さきほどGoogleの44Fの受付の方に「何時まで受付の方いますか？」と聞いたところ、「18:00までです。」だそうです。

ですので、19:00ごろにエレベータで44Fまで上がってきた後に、受付に入ろうとしても扉がしまっています...。

ですので、44Fのエレベータを降りたところまで、私が迎えにいきます！とりあえず、いったん、19:05くらいにいったん様子をみにいくようにしますね。:) もしはやくついた、または遅れそうなときは、到着したタイミングで連絡ください。迎えにいきます。

**Comment by YunaShibata0503** [comment]
了解です！ありがとうございます！

2018年6月26日(火) 15:59 Hayato Ito <notifications@github.com>:

**Comment by kochigami** [comment]
副村長へ

今日のオフィスアワーで，
- １．collaboratorへの追加
- ２．README.mdの村人紹介で，自分の分を追加（gitの練習）
をやったよ！
みんながやろうとしていることは #9 にあるよ．
説明が足りていない所があったら何でもissueに書いてね！！

１は村長からメールが来ていると思うので，acceptみたいなものをクリックすると追加されるよ．

2は #5  に書いたものの更新版を載せるね．
手元のレポジトリ，変なことになっちゃったら，まるごと消してgit cloneからやり直すと色々解決するかも．

[村長のレポジトリ](https://github.com/Hinako-Suzuki/google-step-tsp)か
[大元のレポジトリ](https://github.com/hayatoito/google-step-tsp) をフォークしてね．

後は全部手元のパソコンの端末で打つ．

- 村長のレポジトリを手元にクローン
`git clone https://...`

- 端末で取ってきたレポジトリに移動
例　`cd google-step-tsp`

以下，プルリクエストを送るための準備
- とりあえずマスターブランチを更新
`git checkout master`
`git pull`
- 作業用ブランチを切る (git checkout -b <自分で名前をつける ここではpull-request-test にする>)
`git checkout -b pull-request-test`

- ファイルの編集（今回はREADMEを編集（村人紹介の追加））
(emacs README.md とか，何でもok)

- git add してプルリクエストしたいファイルを追加
`git add README.md`
 
- git commit で編集内容を説明する
`git commit -m "[README.md] 村人紹介の型を追加"`
（日本語で書いたけど，英語で書いてもよいと思う．）

- git push で手元PCから，村長のパソコンに表示されているレポジトリに送る
`git push origin pull-request-test`
(git branchで，自分の居場所が分かる．
`git branch`と打つと，
=>
 ```
master
* pull-request-test
```
みたいに出る)

ここからは，端末を使わない．
自分や村長のgithubのページに表示されている，フォークした画面でやる．
- プルリクエストを送る
githubの自分のレポジトリを見ると，プルリクエストを送ろうみたいなマーク（文字）が出る．
出なかったらNew Pull requestみたいな緑色のボタンを押すと良い．
（今は kochigamiのpull-request-testから，村長のmasterにプルリクエストを送る．）
=> 村長の所にするのに，いちいち選択し直さないといけないと思う．何もしないと，大元の方に送られてしまうかも．
下の写真のComparing changes の真下に，切り替えボタンみたいなのがあって，クリックすると，切り替えられるよ．
base fork; Hinako-Suzuki/google-step-tsp ってなっているところ．多分元はhayatoito/google-step-tsp になっていると思う．

![screenshot from 2018-06-26 14 47 17](https://user-images.githubusercontent.com/7259671/41891754-a756b372-7950-11e8-9c68-e2e3d65e3399.png)
![screenshot from 2018-06-26 14 47 37](https://user-images.githubusercontent.com/7259671/41891755-a7862698-7950-11e8-9815-f7f3046ef14c.png)
![screenshot from 2018-06-26 14 48 15](https://user-images.githubusercontent.com/7259671/41891756-a7a9010e-7950-11e8-8480-2566f8372b14.png)

**Comment by kandmk** [comment]
base fork; Hinako-Suzuki/google-step-tspにしてみると二枚目のスクリーンショット見たくなって何もpull requestできなくなってしまいます。hayatoito/google-step-tspだと三枚目見たくなるのですが....

**Comment by kandmk** [comment]
@kochigami できました！お騒がせしました！色々、本当にありがとうございます！

**Comment by kochigami** [comment]
今頃の返信でごメーん！（ヤギだけに）
みんなできたっぽいので閉じます :)
